GET https://web-nang-cao.herokuapp.com/lab5/users

### 
POST http://web-nang-cao.herokuapp.com/lab5/users
content-type: application/json

{
    "name": "Khoa Henry",
    "age": 20,
    "gender": "male",
    "email": "khoa@gmail.com"
}

###
PUT http://web-nang-cao.herokuapp.com/lab5/users
content-type: application/json

{
    "id":"caZj3f5KyKz4pgCU9sLgbi",
    "name":"Phan Thị Thu Thảo2",
    "age":26,"gender":"female",
    "email":"thao@gmail.com"
}


###
GET https://web-nang-cao.herokuapp.com/lab5/users/i8ZEjHdEyhxmZGZnBiJ8ua

###
DELETE https://web-nang-cao.herokuapp.com/lab5/users/2